//
//  MusicTasksBass.swift
//  MusicTheoryApp
//
//  Created by Лилия Левина on 05.09.2020.
//  Copyright © 2020 Лилия Левина. All rights reserved.
//

import UIKit

class MusicTasksBass {
    var tasks: [MusicTask] = [
        MusicTaskSelectNote(
            questionText: "Выберите ноты большой октавы, расположенные на основных линейках нотного стана",
            notesArray:[Note(name:.Do, tone:.none, duration:.whole),
                        Note(name:.re, tone:.none, duration:.whole),
                        Note(name:.mi, tone:.none, duration:.whole),
                        Note(name:.fa, tone:.none, duration:.whole),
                        Note(name:.sol, tone:.none, duration:.whole),
                        Note(name:.la, tone:.none, duration:.whole),
                        Note(name:.si, tone:.none, duration:.whole)],
            rightAnswer: [.sol, .si],
            cleff: CleffTypes.Bass),
        MusicTaskSelectNote(
                questionText: "Выберите ноты большой октавы, расположенные между линейками нотного стана",
                notesArray:[Note(name:.Do, tone:.none, duration:.whole),
                            Note(name:.re, tone:.none, duration:.whole),
                            Note(name:.mi, tone:.none, duration:.whole),
                            Note(name:.fa, tone:.none, duration:.whole),
                            Note(name:.sol, tone:.none, duration:.whole),
                            Note(name:.la, tone:.none, duration:.whole),
                            Note(name:.si, tone:.none, duration:.whole)],
                rightAnswer: [.la],
                cleff: CleffTypes.Bass),
        MusicTaskSelectNote(
            questionText: "Выберите ноты малой октавы, расположенные на основных линейках нотного стана",
            notesArray: [ Note(name: .Do1, tone: .none, duration: .whole),
                          Note(name: .re1, tone: .none, duration: .whole),
                          Note(name: .mi1, tone: .none, duration: .whole),
                          Note(name: .fa1, tone: .none, duration: .whole),
                          Note(name: .sol1, tone: .none, duration: .whole),
                          Note(name: .la1, tone: .none, duration: .whole),
                          Note(name: .si1, tone: .none, duration: .whole)],
            rightAnswer: [.re1, .fa1, .la1],
            cleff: CleffTypes.Bass),
        MusicTaskSelectNote(
            questionText: "Выберите ноты малой октавы, расположенные между линейками нотного стана",
            notesArray: [ Note(name: .Do1, tone: .none, duration: .whole),
                          Note(name: .re1, tone: .none, duration: .whole),
                          Note(name: .mi1, tone: .none, duration: .whole),
                          Note(name: .fa1, tone: .none, duration: .whole),
                          Note(name: .sol1, tone: .none, duration: .whole),
                          Note(name: .la1, tone: .none, duration: .whole),
                          Note(name: .si1, tone: .none, duration: .whole)],
            rightAnswer: [.Do1, .mi1, .sol1],
            cleff: CleffTypes.Bass),
        MusicTaskSelectNote(
            questionText: "Выберите все ноты ноты ФА большой и малой октавы",
            notesArray:[Note(name:.fa, tone:.none, duration:.whole),
                        Note(name:.mi1, tone:.none, duration:.whole),
                        Note(name:.fa1, tone:.none, duration:.whole),
                        Note(name:.Do1, tone:.none, duration:.whole),
                        Note(name:.sol, tone:.none, duration:.whole),
                        Note(name:.si, tone:.none, duration:.whole),
                        Note(name:.fa1, tone:.none, duration:.whole)],
            rightAnswer: [.fa, .fa1, .fa1],
            cleff: CleffTypes.Bass),
        MusicTaskSelectNote(
                 questionText: "Выберите все ноты ноты ЛЯ большой и малой октавы",
                 notesArray:[Note(name:.fa, tone:.none, duration:.whole),
                             Note(name:.la, tone:.none, duration:.whole),
                             Note(name:.Do1, tone:.none, duration:.whole),
                             Note(name:.la1, tone:.none, duration:.whole),
                             Note(name:.sol1, tone:.none, duration:.whole),
                             Note(name:.la, tone:.none, duration:.whole),
                             Note(name:.fa1, tone:.none, duration:.whole)],
                 rightAnswer: [.la, .la1, .la],
                 cleff: CleffTypes.Bass),
        MusicTaskShowNoteOnThePiano(questionText:"Нажмите на нужную ноту", note: Note(name:.Do, tone: .none, duration: .whole), cleff: CleffTypes.Bass),
        MusicTaskShowNoteOnThePiano(questionText:"Нажмите на нужную ноту", note: Note(name:.fa, tone: .none, duration: .whole), cleff: CleffTypes.Bass),
        MusicTaskShowNoteOnThePiano(questionText:"Нажмите на нужную ноту", note: Note(name:.re1, tone: .none, duration: .whole), cleff: CleffTypes.Bass),
        MusicTaskShowNoteOnThePiano(questionText:"Нажмите на нужную ноту", note: Note(name:.sol1, tone: .none, duration: .whole), cleff: CleffTypes.Bass),
          MusicTaskShowNoteOnThePiano(questionText:"Нажмите на нужную ноту", note: Note(name:.si1, tone: .none, duration: .whole), cleff: CleffTypes.Bass),
          MusicTaskSelectNoteInWord(questionText: "Какая нота большой октавы спряталась в слове?",
                                notesArray: [
                                  Note(name:.Do, tone:.none, duration:.whole),
                                  Note(name:.re, tone:.none, duration:.whole),
                                  Note(name:.mi, tone:.none, duration:.whole),
                                  Note(name:.fa, tone:.none, duration:.whole),
                                  Note(name:.sol, tone:.none, duration:.whole),
                                  Note(name:.la, tone:.none, duration:.whole),
                                  Note(name:.si, tone:.none, duration:.whole)
          ],
                                partsOfWord:[("Ва",nil),
                                             ("си",Note(name: .si, tone:.none, duration: .whole)),
                                             ("лёк",nil)],
                                needToType: false,
                                cleff: CleffTypes.Bass),
          MusicTaskSelectNoteInWord(questionText: "Какая нота большой октавы спряталась в слове?",
                                notesArray: [
                                  Note(name:.Do, tone:.none, duration:.whole),
                                  Note(name:.re, tone:.none, duration:.whole),
                                  Note(name:.mi, tone:.none, duration:.whole),
                                  Note(name:.fa, tone:.none, duration:.whole),
                                  Note(name:.sol, tone:.none, duration:.whole),
                                  Note(name:.la, tone:.none, duration:.whole),
                                  Note(name:.si, tone:.none, duration:.whole)
          ],
                                partsOfWord:[("Кана",nil),
                                             ("ре",Note(name: .re, tone:.none, duration: .whole)),
                                             ("йка",nil)],
                                needToType: false,
                                cleff: CleffTypes.Bass),
          MusicTaskSelectNoteInWord(questionText: "Какая нота малой октавы спряталась в слове?",
                                notesArray: [
                                  Note(name:.Do1, tone:.none, duration:.whole),
                                  Note(name:.re1, tone:.none, duration:.whole),
                                  Note(name:.mi1, tone:.none, duration:.whole),
                                  Note(name:.fa1, tone:.none, duration:.whole),
                                  Note(name:.sol1, tone:.none, duration:.whole),
                                  Note(name:.la1, tone:.none, duration:.whole),
                                  Note(name:.si1, tone:.none, duration:.whole)
          ],
                                partsOfWord:[("Ш",nil),
                                             ("ля",Note(name: .la1, tone:.none, duration: .whole)),
                                             ("па",nil)],
                                needToType: false,
                                cleff: CleffTypes.Bass),
          MusicTaskSelectNoteInWord(questionText: "Какая нота малой октавы спряталась в слове?",
                                notesArray: [
                                  Note(name:.Do1, tone:.none, duration:.whole),
                                  Note(name:.re1, tone:.none, duration:.whole),
                                  Note(name:.mi1, tone:.none, duration:.whole),
                                  Note(name:.fa1, tone:.none, duration:.whole),
                                  Note(name:.sol1, tone:.none, duration:.whole),
                                  Note(name:.la1, tone:.none, duration:.whole),
                                  Note(name:.si1, tone:.none, duration:.whole)
          ],
                                partsOfWord:[("До",Note(name: .Do1, tone:.none, duration: .whole)),
                                             ("ждь",nil)],
                                needToType: false,
                                cleff: CleffTypes.Bass),
          MusicTaskSelectNoteInWord(questionText: "Какая нота большой октавы спряталась в слове?",
                                        notesArray: [
                                          Note(name:.Do, tone:.none, duration:.whole),
                                          Note(name:.re, tone:.none, duration:.whole),
                                          Note(name:.mi, tone:.none, duration:.whole),
                                          Note(name:.fa, tone:.none, duration:.whole),
                                          Note(name:.sol, tone:.none, duration:.whole),
                                          Note(name:.la, tone:.none, duration:.whole),
                                          Note(name:.si, tone:.none, duration:.whole)
                  ],
                                        partsOfWord:[("Сара",nil),
                                                     ("фа",Note(name: .fa, tone:.none, duration: .whole)),
                                                     ("н",nil)],
                                        needToType: false,
                                        cleff: CleffTypes.Bass),
          MusicTaskSelectNoteInWord(questionText: "Какая нота большой октавы спряталась в слове?",
                                                notesArray: [
                                                  Note(name:.Do, tone:.none, duration:.whole),
                                                  Note(name:.re, tone:.none, duration:.whole),
                                                  Note(name:.mi, tone:.none, duration:.whole),
                                                  Note(name:.fa, tone:.none, duration:.whole),
                                                  Note(name:.sol, tone:.none, duration:.whole),
                                                  Note(name:.la, tone:.none, duration:.whole),
                                                  Note(name:.si, tone:.none, duration:.whole)
                          ],
                                                partsOfWord:[("Ми",Note(name: .mi, tone:.none, duration: .whole)),
                                                             ("моза",nil)],
                                                needToType: false,
                                                cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Какая нота малой октавы спряталась в слове?",
                                   notesArray: [
                                     Note(name:.Do1, tone:.none, duration:.whole),
                                     Note(name:.re1, tone:.none, duration:.whole),
                                     Note(name:.mi1, tone:.none, duration:.whole),
                                     Note(name:.fa1, tone:.none, duration:.whole),
                                     Note(name:.sol1, tone:.none, duration:.whole),
                                     Note(name:.la1, tone:.none, duration:.whole),
                                     Note(name:.si1, tone:.none, duration:.whole)
             ],
                                   partsOfWord:[("Огу",nil),
                                                ("ре",Note(name: .re1, tone:.none, duration: .whole)),
                                                ("ц",nil)],
                                   needToType: false,
                                   cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Какая нота малой октавы спряталась в слове?",
                                   notesArray: [
                                     Note(name:.Do1, tone:.none, duration:.whole),
                                     Note(name:.re1, tone:.none, duration:.whole),
                                     Note(name:.mi1, tone:.none, duration:.whole),
                                     Note(name:.fa1, tone:.none, duration:.whole),
                                     Note(name:.sol1, tone:.none, duration:.whole),
                                     Note(name:.la1, tone:.none, duration:.whole),
                                     Note(name:.si1, tone:.none, duration:.whole)
             ],
                                   partsOfWord:[("Рас",nil),
                                                ("соль",Note(name: .sol1, tone:.none, duration: .whole)),
                                                ("ник",nil)],
                                   needToType: false,
                                   cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                        notesArray: [ Note(name:.si, tone:.none, duration:.whole)],
                                        partsOfWord: [
                                          ("Апель",nil),
                                          ("си",Note(name: .si, tone: .none, duration: .whole)),
                                          ("н",nil)],
                                        needToType: true,
                                        cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                         notesArray: [ Note(name:.re, tone:.none, duration:.whole)],
                                         partsOfWord: [
                                           ("Ап",nil),
                                           ("ре",Note(name: .re, tone: .none, duration: .whole)),
                                           ("ль",nil)],
                                         needToType: true,
                                         cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                         notesArray: [ Note(name:.la, tone:.none, duration:.whole)],
                                         partsOfWord: [
                                           ("По",nil),
                                           ("ля",Note(name: .la, tone: .none, duration: .whole)),
                                           ("на",nil)],
                                         needToType: true,
                                         cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                               notesArray: [ Note(name:.Do1, tone:.none, duration:.whole)],
                                               partsOfWord: [
                                                 ("По",nil),
                                                 ("до",Note(name: .Do1, tone: .none, duration: .whole)),
                                                 ("рожник",nil)],
                                               needToType: true,
                                               cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                               notesArray: [ Note(name:.re1, tone:.none, duration:.whole)],
                                               partsOfWord: [
                                                 ("Де",nil),
                                                 ("ре",Note(name: .re1, tone: .none, duration: .whole)),
                                                 ("во",nil)],
                                               needToType: true,
                                               cleff: CleffTypes.Bass),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                               notesArray: [ Note(name:.la1, tone:.none, duration:.whole)],
                                               partsOfWord: [
                                                 ("К",nil),
                                                 ("ля",Note(name: .la1, tone: .none, duration: .whole)),
                                                 ("кса",nil)],
                                               needToType: true,
                                               cleff: CleffTypes.Bass)
    ]
}
