//
//  MusicTasks.swift
//  MusicTheoryApp
//
//  Created by Лилия Левина on 20.05.2020.
//  Copyright © 2020 Лилия Левина. All rights reserved.
//

import UIKit

class MusicTasks {
    var tasks: [MusicTask] = [
        MusicTaskSelectNote(
            questionText: "Выберите ноты 1-й октавы, расположенные на основных линейках нотного стана",
            notesArray: [ Note(name:.Do, tone:.none, duration:.whole),
                          Note(name:.re, tone:.none, duration:.whole),
                          Note(name:.mi, tone:.none, duration:.whole),
                          Note(name:.fa, tone:.none, duration:.whole),
                          Note(name:.sol, tone:.none, duration:.whole),
                          Note(name:.la, tone:.none, duration:.whole),
                          Note(name:.si, tone:.none, duration:.whole)],
            rightAnswer:   [0,2,4]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 1-й октавы, расположенные на основных линейках нотного стана",
            notesArray:[Note(name:.si, tone:.none, duration:.whole),
                        Note(name:.la, tone:.none, duration:.whole),
                        Note(name:.sol, tone:.none, duration:.whole),
                        Note(name:.fa, tone:.none, duration:.whole),
                        Note(name:.mi, tone:.none, duration:.whole),
                        Note(name:.re, tone:.none, duration:.whole),
                        Note(name:.Do, tone:.none, duration:.whole)],
            rightAnswer:   [0,2,4]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 2-й октавы, расположенные на основных линейках нотного стана",
            notesArray: [ Note(name: .Do1, tone: .none, duration: .whole),
                          Note(name: .re1, tone: .none, duration: .whole),
                          Note(name: .mi1, tone: .none, duration: .whole),
                          Note(name: .fa1, tone: .none, duration: .whole),
                          Note(name: .sol1, tone: .none, duration: .whole),
                          Note(name: .la1, tone: .none, duration: .whole),
                          Note(name: .si1, tone: .none, duration: .whole)],
            rightAnswer: [6,8]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 2-й октавы, расположенные на основных линейках нотного стана",
            notesArray: [Note(name: .si1, tone: .none, duration: .whole),
                         Note(name: .la1, tone: .none, duration: .whole),
                         Note(name: .sol1, tone: .none, duration: .whole),
                         Note(name: .fa1, tone: .none, duration: .whole),
                         Note(name: .mi1, tone: .none, duration: .whole),
                         Note(name: .re1, tone: .none, duration: .whole),
                         Note(name: .Do1, tone: .none, duration: .whole)
            ],
            rightAnswer: [6,8]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 1-й октавы, которые пишутся между линейками нотного стана",
            notesArray: [ Note(name:.Do, tone:.none, duration:.whole),
                          Note(name:.re, tone:.none, duration:.whole),
                          Note(name:.mi, tone:.none, duration:.whole),
                          Note(name:.fa, tone:.none, duration:.whole),
                          Note(name:.sol, tone:.none, duration:.whole),
                          Note(name:.la, tone:.none, duration:.whole),
                          Note(name:.si, tone:.none, duration:.whole)],
            rightAnswer:   [-1,1,3]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 1-й октавы, которые пишутся между линейками нотного стана",
            notesArray:[Note(name:.si, tone:.none, duration:.whole),
                        Note(name:.la, tone:.none, duration:.whole),
                        Note(name:.sol, tone:.none, duration:.whole),
                        Note(name:.fa, tone:.none, duration:.whole),
                        Note(name:.mi, tone:.none, duration:.whole),
                        Note(name:.re, tone:.none, duration:.whole),
                        Note(name:.Do, tone:.none, duration:.whole)],
            rightAnswer:   [-1,1,3]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 2-й октавы, которые пишутся между линейками нотного стана",
            notesArray: [ Note(name: .Do1, tone: .none, duration: .whole),
                          Note(name: .re1, tone: .none, duration: .whole),
                          Note(name: .mi1, tone: .none, duration: .whole),
                          Note(name: .fa1, tone: .none, duration: .whole),
                          Note(name: .sol1, tone: .none, duration: .whole),
                          Note(name: .la1, tone: .none, duration: .whole),
                          Note(name: .si1, tone: .none, duration: .whole)],
            rightAnswer: [3,5]),
        MusicTaskSelectNote(
            questionText: "Выберите ноты 2-й октавы, которые пишутся между линейками нотного стана",
            notesArray: [Note(name: .si1, tone: .none, duration: .whole),
                         Note(name: .la1, tone: .none, duration: .whole),
                         Note(name: .sol1, tone: .none, duration: .whole),
                         Note(name: .fa1, tone: .none, duration: .whole),
                         Note(name: .mi1, tone: .none, duration: .whole),
                         Note(name: .re1, tone: .none, duration: .whole),
                         Note(name: .Do1, tone: .none, duration: .whole)
            ],
            rightAnswer: [3,5]),
        MusicTaskShowNoteOnThePiano(questionText:"Нажмите на нужную ноту", note: Note(name:.fa, tone: .none, duration: .whole)),
        MusicTaskSelectNoteInWord(questionText: "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord:[("Ли",nil),
                                               ("си",Note(name: .si, tone:.none, duration: .whole)),
                                               ("ца",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [("Ху",nil),
                                                ("до",Note(name:.Do, tone: .none, duration: .whole)),
                                                ("жник",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [("Зем",nil),
                                                ("ля",Note(name: .la, tone: .none, duration: .whole)),
                                                ("ника",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [("Ал",nil),
                                                ("фа",Note(name: .fa, tone: .none, duration: .whole)),
                                                ("вит",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [("Ось",nil),
                                                ("ми",Note(name: .mi, tone: .none, duration: .whole)),
                                                ("ног",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [("Ст",nil),
                                                ("ре",Note(name: .re, tone: .none, duration: .whole)),
                                                ("коза",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [
                                    ("Соль",Note(name: .sol, tone: .none, duration: .whole)),
                                    ("феджио",nil)]),
        MusicTaskSelectNoteInWord(questionText:  "Какая нота спряталась в слове?",
                                  notesArray: [
                                    Note(name:.Do, tone:.none, duration:.whole),
                                    Note(name:.re, tone:.none, duration:.whole),
                                    Note(name:.mi, tone:.none, duration:.whole),
                                    Note(name:.fa, tone:.none, duration:.whole),
                                    Note(name:.sol, tone:.none, duration:.whole),
                                    Note(name:.la, tone:.none, duration:.whole),
                                    Note(name:.si, tone:.none, duration:.whole)
            ],
                                  partsOfWord: [("Бе",nil),
                                                ("ре",Note(name: .re, tone: .none, duration: .whole)),
                                                ("г",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.si, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("Cи",Note(name: .si, tone: .none, duration: .whole)),
                                    ("ница",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.re1, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("Че",nil),
                                    ("ре",Note(name: .re1, tone: .none, duration: .whole)),
                                    ("паха",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.la, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("Ля",Note(name: .la, tone: .none, duration: .whole)),
                                    ("гушка",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.fa1, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("Фа",Note(name: .fa1, tone: .none, duration: .whole)),
                                    ("кел",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.Do1, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("До",Note(name: .Do1, tone: .none, duration: .whole)),
                                    ("рога",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.si0, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("Си",Note(name:.si0, tone: .none, duration: .whole)),
                                    ("роп",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.mi, tone:.none, duration:.whole)],
                                  partsOfWord: [
                                    ("Ми",Note(name:.mi, tone: .none, duration: .whole)),
                                    ("нута",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.mi1, tone:.none, duration:.whole)],
                                  partsOfWord: [("Пира",nil),
                                                ("ми",Note(name:.mi1, tone: .none, duration: .whole)),
                                                ("да",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.fa1, tone:.none, duration:.whole)],
                                  partsOfWord: [("Фа",Note(name:.fa1, tone: .none, duration: .whole)),
                                                ("нтазия",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.fa, tone:.none, duration:.whole),
                                                Note(name:.sol1, tone:.none, duration:.whole)],
                                  partsOfWord: [("Фа",Note(name:.fa, tone: .none, duration: .whole)),
                                                ("соль",Note(name:.sol1, tone: .none, duration: .whole))]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.fa, tone:.none, duration:.whole),
                                                Note(name:.sol1, tone:.none, duration:.whole)],
                                  partsOfWord: [("Фа",Note(name:.fa, tone: .none, duration: .whole)),
                                                ("соль",Note(name:.sol1, tone: .none, duration: .whole))]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.mi1, tone:.none, duration:.whole),
                                                Note(name:.Do, tone:.none, duration:.whole)],
                                  partsOfWord: [("По",nil),
                                                ("ми",Note(name:.mi1, tone: .none, duration: .whole)),
                                                ("до",Note(name:.Do, tone: .none, duration: .whole)),
                                                ("р",nil)]),
        MusicTaskSelectNoteInWord(questionText: "Разгадайте слово, зашифрованное с помощью нот",
                                  notesArray: [ Note(name:.la1, tone:.none, duration:.whole)],
                                  partsOfWord: [("Свет",nil),
                                                ("ля",Note(name:.la1, tone: .none, duration: .whole)),
                                                ("чок",nil)])
    ]
}
